# workflow which lints and checks the rust code on every push and pull request
name: Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: checkout
        uses: actions/checkout@v3

      # https://github.com/pre-commit/action
      - name: run pre-commit
        uses: pre-commit/action@v3.0.0
        env:
          SKIP: no-commit-to-branch
