name: lint
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: yamllint
        run: >-
          docker run
          --rm
          --volume "$(pwd):/work"
          backplane/yamllint
          -f github
          .

      - name: make lint
        run: >-
          docker run
          --rm
          --volume "$(pwd):/work"
          --workdir /work
          backplane/goenv
          make lint
